### ISSUE TITLE
Feature request: configuration files

### ISSUE THREAD

**Issue by tbodt** [ogham/exa#511]
Having to configure exa using a shell alias is less than convenient. ripgrep allows you to set a RIPGREP_CONFIG_PATH environment variable to point to a file that contains a list of default options, one per line (https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file). I think exa should do this too.

**Comment by bkuhlmann** [comment]
I would like this too. One suggestion would be to adhere to the [XDG](https://www.alchemists.io/projects/xdg) specification so our Dotfiles don't get so cluttered. With XDG, we could have this instead: `~/.config/exa/configuration.yml`. :tada:

*NOTE: Doesn't have to be a YAML configuration but can be any configuration format that makes sense.*

**Comment by ariasuni** [comment]
Here’s a suggested, hypothetical config file, inspired by [ui_styles.rs](https://github.com/ogham/exa/blob/v0.10.0/src/theme/ui_styles.rs)/[default_theme.rs](https://github.com/ogham/exa/blob/v0.10.0/src/theme/default_theme.rs):

<details><summary><code>~/.config/exa/exa.toml</code></summary>

```toml
# The [colors] table has all that’s possible to configure with EXA_COLORS
# and filekinds too, in a much more readable way!!

[colors.ui]
punctuation = "black bold"
# date = ""
# inode = ""
# blocks = ""
# header = ""
# link_path = ""
# control_char = ""
# broken_path = ""

[colors.filetypes]
# file = ""
# directory = ""
# executable = ""
# pipe = ""
# socket = ""
# block_device = ""
# char_device = ""
# symlink = ""
# broken_symlink = ""

[colors.filekinds]
temp = "white"
# build = "yellow bold"
image = "purple"
video = "purple bold"
music = "cyan"
lossless = "cyan bold"
crypto = "green bold"
document = "green"
# compressed = "red"
compiled = "yellow"

[colors.perms]
# ur = ""
# uw = ""
# ux_file = ""
# ux_other = ""
# gr = ""
# gw = ""
# gx = ""
# or = ""
# ow = ""
# ox = ""
# special_user_file = ""
# special_other = ""
# extended_attribute = ""

[colors.sizes]
# the two first are default, and overridden by the more specific variants.
# nums = ""
# units = ""
num-byte = "green"
num-kilo = "green bold"
num-mega = "yellow"
num-giga = "red"
num-huge = "purple"
unit-byte = "green"
unit-kilo = "green bold"
unit-mega = "yellow"
unit-giga = "red"
unit-huge = "purple"
# major = ""
# minor = ""

[colors.users]
# user-you = ""
# user-other = ""
# group-yours = ""
# group-other = ""

[colors.links]
# normal = ""
# multi = ""

[colors.git]
# new = ""
# modified = ""
# deleted = ""
# renamed = ""
# changed = ""

## The [[ and ]] signals that colors.custom is an array of table.
[[colors.custom]]
patterns = ["*.md", "*.rst"]
style = "yellow bold"

[[colors.custom]]
patterns = [".py"]
style = "red underline"


## Everything else that was controlled by environment variables.
[options]
# columns =
strict = true
# grid_rows
# icon_spacing
```
</details>

I’m not sure about some names (I’m totally not sure what’s `special_user_file` and `special_other`, and if the same distinction between `ux_file` and `ux_other`).

But mostly I think it’s an interesting draft. Any thoughts?
